source 'https://github.com/DoNewsCode/DNSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

#platform :ios, '9.0'

target 'DNChannelPage_Example' do
  pod 'DNChannelPage', :path => '../'

  target 'DNChannelPage_Tests' do
    inherit! :search_paths

    
  end
end
